const API_URL = 'http://localhost:3000';

document.addEventListener('DOMContentLoaded', () => {
    updateAuthHeader();

    // === ГЕНЕРАЦИЯ МЕНЮ АДМИНА ===
    try {
        const userRaw = localStorage.getItem('currentUser');
        if (userRaw) {
            const currentUser = JSON.parse(userRaw);
            if (currentUser.role === 'admin' || currentUser.role === 'administrator') {
                const mainNav = document.querySelector('.main-nav');
                if (mainNav && !document.querySelector('.admin-menu-link')) {
                    const adminLi = document.createElement('li');
                    adminLi.className = 'admin-menu-item';
                    const adminLink = document.createElement('a');
                    adminLink.href = 'admin.html';
                    adminLink.className = 'admin-menu-link';
                    adminLink.innerHTML = '</i> Редактор';
                    adminLi.appendChild(adminLink);
                    mainNav.appendChild(adminLi);
                }
            }
        }
    } catch (e) { console.error(e); }

    // === ПЕРЕКЛЮЧЕНИЕ ВКЛАДОК ===
    const tabButtons = document.querySelectorAll('.tab-btn');
    const authForms = document.querySelectorAll('.auth-form');

    tabButtons.forEach(button => {
        button.addEventListener('click', () => {
            tabButtons.forEach(btn => btn.classList.remove('active'));
            authForms.forEach(form => form.classList.remove('active'));
            button.classList.add('active');
            const targetForm = document.getElementById(button.getAttribute('data-tab'));
            if (targetForm) targetForm.classList.add('active');
        });
    });

    // ==========================================
    // === ЛОГИКА ФОРМЫ РЕГИСТРАЦИИ ===
    // ==========================================
    const regForm = document.getElementById('register-form');
    if (regForm) regForm.setAttribute('novalidate', 'true');

    const fields = {
        lastName: document.getElementById('reg-lastname'),
        firstName: document.getElementById('reg-firstname'),
        middleName: document.getElementById('reg-middlename'),
        email: document.getElementById('reg-email'),
        phone: document.getElementById('reg-phone'),
        birthdate: document.getElementById('reg-birthday'),
        password: document.getElementById('reg-password'),
        confirmPassword: document.getElementById('reg-password-confirm'),
        nickname: document.getElementById('reg-nickname'),
        agreement: document.getElementById('reg-agreement') // Наша галочка
    };

    const errors = {
        lastName: document.getElementById('err-lastname'),
        firstName: document.getElementById('err-firstname'),
        email: document.getElementById('err-email'),
        phone: document.getElementById('err-phone'),
        birthdate: document.getElementById('err-birthday'),
        password: document.getElementById('err-password'),
        confirmPassword: document.getElementById('err-password-confirm'),
        nickname: document.getElementById('err-nickname')
    };

    const btnSubmit = document.getElementById('btn-register-submit');
    const btnGenerateNick = document.getElementById('btn-generate-nick');
    const attemptsHint = document.getElementById('nick-attempts-left');
    
    let nickAttempts = 5;
    let autoGeneratedPassword = "";

    // === ЖЕСТКАЯ БЛОКИРОВКА КНОПКИ ПРИ СТАРТЕ ===
    if (btnSubmit) {
        btnSubmit.disabled = true;
    }

    function showError(fieldKey, message) {
        if (errors[fieldKey]) errors[fieldKey].textContent = message;
    }
    function clearError(fieldKey) {
        if (errors[fieldKey]) errors[fieldKey].textContent = '';
    }

    function validateAge(birthdateString) {
        if (!birthdateString) return false;
        const birthDate = new Date(birthdateString);
        const today = new Date();
        let age = today.getFullYear() - birthDate.getFullYear();
        const monthDiff = today.getMonth() - birthDate.getMonth();
        if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
            age--;
        }
        return age >= 16;
    }

    // === ФИЛЬТРАЦИЯ ВВОДА НА ЛЕТУ ===
    ['lastName', 'firstName', 'middleName'].forEach(key => {
        if (fields[key]) {
            fields[key].addEventListener('input', (e) => {
                e.target.value = e.target.value.replace(/[^a-zA-Zа-яА-ЯёЁ\s\-]/g, '');
            });
        }
    });

    if (fields.nickname) {
        fields.nickname.addEventListener('input', (e) => {
            if (e.target.value.length > 12) {
                e.target.value = e.target.value.substring(0, 12);
            }
        });
    }

    if (fields.phone) {
        fields.phone.addEventListener('focus', () => {
            if (!fields.phone.value.trim()) fields.phone.value = '+375';
        });
        fields.phone.addEventListener('input', () => {
            let val = fields.phone.value.replace(/[^\d+]/g, '');
            if (!val.startsWith('+375')) val = '+375' + val.replace('+375', '');
            if (val.length > 13) val = val.substring(0, 13);
            fields.phone.value = val;
        });
    }

    // === ВАЛИДАЦИЯ ОТДЕЛЬНЫХ ПОЛЕЙ ===
    function validateField(key) {
        if (!fields[key]) return true;
        const val = fields[key].value.trim();

        switch (key) {
            case 'lastName':
                if (!val) { showError(key, 'Введите фамилию'); return false; }
                clearError(key); return true;
                
            case 'firstName':
                if (!val) { showError(key, 'Введите имя'); return false; }
                clearError(key); return true;
                
            case 'email':
                const emailRegex = /^[^\s@]+@[^\s@]+\.[a-zA-Z]{2,}$/;
                if (!emailRegex.test(val)) { showError(key, 'Некорректный email. Требуется @ и домен (например .com)'); return false; }
                clearError(key); return true;
                
            case 'phone':
                if (val.length !== 13 || !val.startsWith('+375')) { 
                    showError(key, 'Телефон должен содержать +375 и ровно 9 цифр'); 
                    return false; 
                }
                clearError(key); return true;
                
            case 'birthdate':
                if (!val) { showError(key, 'Укажите дату рождения'); return false; }
                if (!validateAge(val)) { showError(key, 'Регистрация доступна только с 16 лет'); return false; }
                clearError(key); return true;
                
            case 'nickname':
                if (val.length < 3) { showError(key, 'Никнейм от 3 символов'); return false; }
                clearError(key); return true;

            case 'password':
                const passRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}$/;
                if (!passRegex.test(val)) { 
                    showError(key, 'Мин. 6 символов: заглавная, строчная, цифра и спецсимвол'); 
                    return false; 
                }
                clearError(key);
                if (fields.confirmPassword && fields.confirmPassword.value) validateField('confirmPassword');
                return true;
                
            case 'confirmPassword':
                if (val !== fields.password.value) {
                    showError(key, 'Пароли не совпадают');
                    return false;
                }
                clearError(key); return true;
                
            default: return true;
        }
    }

    // === ПРОВЕРКА ВСЕЙ ФОРМЫ ===
    function checkFormValidity() {
        if (!regForm) return;

        const isLastNameOk = fields.lastName && fields.lastName.value.trim() !== '';
        const isFirstNameOk = fields.firstName && fields.firstName.value.trim() !== '';
        const isEmailOk = fields.email && /^[^\s@]+@[^\s@]+\.[a-zA-Z]{2,}$/.test(fields.email.value.trim());
        const isPhoneOk = fields.phone && fields.phone.value.trim().length === 13;
        const isBirthdateOk = fields.birthdate && fields.birthdate.value !== '' && validateAge(fields.birthdate.value);
        const isNicknameOk = fields.nickname && fields.nickname.value.trim().length >= 3 && fields.nickname.value.trim().length <= 12;
        const isPasswordOk = fields.password && /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}$/.test(fields.password.value);
        const isConfirmOk = fields.confirmPassword && fields.confirmPassword.value !== '' && fields.confirmPassword.value === fields.password.value;
        const isAgreementOk = fields.agreement && fields.agreement.checked; // Проверяем галочку

        const isFormValid = isLastNameOk && isFirstNameOk && isEmailOk && isPhoneOk && 
                            isBirthdateOk && isPasswordOk && isConfirmOk && 
                            isAgreementOk && isNicknameOk;

        if (btnSubmit) {
            btnSubmit.disabled = !isFormValid; // Если всё true, кнопка разблокируется
        }
    }

    Object.keys(fields).forEach(key => {
        if (!fields[key]) return;
        const eventType = (key === 'agreement' || key === 'birthdate') ? 'change' : 'input';
        fields[key].addEventListener(eventType, () => {
            validateField(key);
            checkFormValidity();
        });
    });

    // === ГЕНЕРАЦИЯ НИКНЕЙМА ===
    if (btnGenerateNick) {
        btnGenerateNick.addEventListener('click', (e) => {
            e.preventDefault();
            if (nickAttempts <= 0) return;

            const isLastNameValid = fields.lastName.value.trim() !== '';
            const isFirstNameValid = fields.firstName.value.trim() !== '';

            if (!isLastNameValid || !isFirstNameValid) {
                alert('Сначала введите Фамилию и Имя для генерации никнейма!');
                return;
            }

            const ln = fields.lastName.value.trim().toLowerCase();
            const fn = fields.firstName.value.trim().toLowerCase();

            const trans = (str) => {
                const map = { 'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'yo','ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'kh','ц':'ts','ч':'ch','ш':'sh','щ':'shch','ы':'y','э':'e','ю':'yu','я':'ya','ь':'','ъ':'' };
                return str.split('').map(char => map[char] || char).join('');
            };

            const randomNum = Math.floor(100 + Math.random() * 899); 
            let generatedNick = `${trans(fn).substring(0,3)}${trans(ln).substring(0,3)}${randomNum}`;
            
            if (generatedNick.length > 12) {
                generatedNick = generatedNick.substring(0, 12);
            }
            
            fields.nickname.value = generatedNick;
            
            nickAttempts--;
            if (attemptsHint) attemptsHint.textContent = `Осталось попыток генерации: ${nickAttempts}`;

            if (nickAttempts === 0) {
                btnGenerateNick.disabled = true;
                if (attemptsHint) attemptsHint.textContent = "Попытки исчерпаны.";
            }

            validateField('nickname');
            checkFormValidity();
        });
    }

    // === РАДИОКНОПКИ ГЕНЕРАЦИИ ПАРОЛЯ ===
    const passMethodRadios = document.querySelectorAll('input[name="pass-method"]');
    passMethodRadios.forEach(radio => {
        radio.addEventListener('change', (e) => {
            if (e.target.value === 'auto') {
                const upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                const lower = "abcdefghijklmnopqrstuvwxyz";
                const digits = "0123456789";
                const specs = "@$!%*?&";
                
                autoGeneratedPassword = 
                    upper.charAt(Math.floor(Math.random() * upper.length)) +
                    lower.charAt(Math.floor(Math.random() * lower.length)) +
                    digits.charAt(Math.floor(Math.random() * digits.length)) +
                    specs.charAt(Math.floor(Math.random() * specs.length));
                    
                const allChars = upper + lower + digits + specs;
                for (let i = 0; i < 4; i++) {
                    autoGeneratedPassword += allChars.charAt(Math.floor(Math.random() * allChars.length));
                }

                autoGeneratedPassword = autoGeneratedPassword.split('').sort(() => 0.5 - Math.random()).join('');

                alert(`ВАШ СГЕНЕРИРОВАННЫЙ ПАРОЛЬ:\n\n${autoGeneratedPassword}\n\nСкопируйте его и введите в поля пароля ниже!`);
                
                if (fields.password) fields.password.value = '';
                if (fields.confirmPassword) fields.confirmPassword.value = '';
            } else {
                autoGeneratedPassword = "";
                if (fields.password) fields.password.value = '';
                if (fields.confirmPassword) fields.confirmPassword.value = '';
            }
            validateField('password');
            validateField('confirmPassword');
            checkFormValidity();
        });
    });

    // === ОТПРАВКА ФОРМЫ РЕГИСТРАЦИИ ===
    if (regForm) {
        regForm.addEventListener('submit', async (e) => {
            e.preventDefault();

            if (btnSubmit.disabled) return;

            const email = fields.email.value.trim().toLowerCase();

            try {
                const checkResponse = await fetch(`${API_URL}/users?email=${email}`);
                const existingUsers = await checkResponse.json();
                
                if (existingUsers.length > 0) {
                    alert('ОШИБКА: Пользователь с таким E-mail уже зарегистрирован!');
                    return;
                }

                const newUser = {
                    id: String(Date.now()), 
                    name: `${fields.lastName.value.trim()} ${fields.firstName.value.trim()} ${fields.middleName ? fields.middleName.value.trim() : ''}`.trim(),
                    email: email, 
                    phone: fields.phone.value.trim(), 
                    birthday: fields.birthdate.value, 
                    nickname: fields.nickname.value.trim(), 
                    password: fields.password.value, 
                    role: "user"
                };

                const response = await fetch(`${API_URL}/users`, {
                    method: 'POST', 
                    headers: { 'Content-Type': 'application/json' }, 
                    body: JSON.stringify(newUser)
                });

                if (response.ok) {
                    alert('Регистрация успешно завершена! Теперь вы можете войти в систему.');
                    regForm.reset();
                    btnSubmit.disabled = true; // Снова блокируем после успешной отправки
                    autoGeneratedPassword = "";
                    
                    const loginTabBtn = document.querySelector('[data-tab="login-form"]');
                    if (loginTabBtn) loginTabBtn.click();
                } else {
                    alert('Ошибка при сохранении пользователя на сервере.');
                }
            } catch (error) {
                console.error('Ошибка сети:', error);
                alert('Не удалось связаться с сервером базы данных (json-server).');
            }
        });
    }

    // ==========================================
    // === ЛОГИКА ВХОДА (АВТОРИЗАЦИЯ) ===
    // ==========================================
    const loginForm = document.getElementById('login-form');
    if (loginForm) {
        loginForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = document.getElementById('login-email').value.trim().toLowerCase();
            const password = document.getElementById('login-password').value;

            try {
                const response = await fetch(`${API_URL}/users?email=${email}`);
                const users = await response.json();
                
                if (users.length > 0 && String(users[0].password) === String(password)) {
                    localStorage.setItem('currentUser', JSON.stringify({
                        id: users[0].id, name: users[0].name, email: users[0].email, role: users[0].role || 'user'
                    }));
                    alert(`Успешный вход! Добро пожаловать, ${users[0].name}.`);
                    updateAuthHeader();
                    window.location.href = 'index.html'; 
                } else {
                    alert('Неверный Email или Пароль!');
                }
            } catch (error) {
                alert('Ошибка соединения с сервером.');
            }
        });
    }
});

// === ОБНОВЛЕНИЕ ШАПКИ ПРИ АВТОРИЗАЦИИ ===
function updateAuthHeader() {
    const authZone = document.getElementById('auth-zone');
    if (!authZone) return;
    const userRaw = localStorage.getItem('currentUser');

    if (userRaw) {
        const user = JSON.parse(userRaw);
        authZone.innerHTML = `
            <div class="auth-user-container">
                <a href="lk.html" class="header-cabinet">
                    <div class="cabinet-icon"><img src="assets/iconoir_profile-circle.png" class="cabinet-icon" alt="Профиль"></div>
                    <div class="cabinet-text"><span class="cabinet-title">${user.name}</span><span class="cabinet-desc">Личный кабинет</span></div>
                </a>
                <span class="auth-separator">|</span>
              <a href="javascript:void(0)" id="logout-btn" style="color: white; text-decoration: none;">Выйти <i class="fa fa-sign-out" style="color: white;"></i></a>
            </div>
        `;
        document.getElementById('logout-btn').addEventListener('click', () => {
            localStorage.removeItem('currentUser');
            window.location.href = 'index.html';
        });
    } else {
        authZone.innerHTML = `
            <a href="auth.html" class="header-cabinet">
                <div class="cabinet-icon"><img src="assets/iconoir_profile-circle.png" class="cabinet-icon" alt="Профиль"></div>
                <div class="cabinet-text"><span class="cabinet-title">Кабинет</span><span class="cabinet-desc">Вход для клиентов</span></div>
            </a>
        `;
    }
}